// --- Comprehensive English Profanity Blocklist ---
// Sourced from a combination of open-source community projects.
const PROFANITY_WORDS = [
  "ahole", "anus", "arse", "ass", "ass-fucker", "asses", "assfucker", "asshole",
  "assholes", "autoerotic", "ballsack", "balls", "bastard", "beastial", "beastiality",
  "bellend", "bestial", "bestiality", "bitch", "bitches", "bitching", "biatch",
  "bloody", "blowjob", "blow job", "bollock", "bollok", "boner", "boob", "boobs",
  "breasts", "buceta", "bugger", "bum", "butt", "butthole", "buttmunch", "buttplug",
  "cawk", "chink", "cipa", "clit", "clitoris", "cnut", "cock", "cock-sucker",
  "cockface", "cockhead", "cockmunch", "cockmuncher", "cocksucker", "cocksucking",
  "coon", "crap", "cum", "cummer", "cumshot", "cumslut", "cunt", "cuntlicker",
  "cuntlicking", "cunts", "cyalis", "cyberfuc", "cyberfuck", "cyberfucker",
  "cyberfucking", "damn", "dick", "dickhead", "dildo", "dildos", "dink", "dirsa",
  "dlck", "dog-fucker", "dogging", "doggy style", "donkeyribber", "doosh", "duche",
  "dyke", "ejaculate", "ejaculating", "ejaculation", "fag", "faggot", "fagging",
  "faggitt", "faggot", "faggs", "fagot", "fagots", "fanny", "fannyflaps",
  "fannyfucker", "fanyy", "fatass", "fcuk", "fcuker", "fcuking", "feck",
  "fecker", "felching", "fellate", "fellatio", "fingerfuck", "fingerfucker",
  "fingerfucking", "fistfuck", "fistfucker", "fistfucking", "flange", "fook",
  "fooker", "fuck", "fucka", "fucked", "fucker", "fuckers", "fuckhead", "fuckheads",
  "fuckin", "fucking", "fuckings", "fuckme", "fucks", "fuckwhit", "fuckwit",
  "fudgepacker", "fudge packer", "fuk", "fuker", "fukker", "fukkin", "fuks",
  "fukwhit", "fukwit", "fux", "fuxor", "gangbang", "gangbanged", "gangbangs",
  "gaylord", "gaysex", "goatse", "god-dam", "god-damned", "goddamn", "god damn",
  "hardcoresex", "hell", "heshe", "hoar", "hoare", "hoer", "homo", "hore",
  "horny", "hotsex", "jack-off", "jackoff", "jap", "jerk-off", "jism", "jiz",
  "jizm", "jizz", "kawk", "knob", "knobead", "knobed", "knobend", "knobhead",
  "knobjocky", "knobjokey", "kock", "kondum", "kondums", "kum", "kummer", "kumming",
  "kums", "kunilingus", "lmfao", "lust", "lusting", "masochist", "masterbate",
  "masterbating", "masterbates", "masturbate", "masturbation", "motherfucker",
  "motherfucking", "motherfucks", "muff", "mutha", "muthafecker", "muthafuckker",
  "muther", "mutherfucker", "nazi", "nigger", "niggers", "nigga", "niggah",
  "niggaz", "nob", "nob jokey", "nobhead", "nobjocky", "nobjokey", "numbnuts",
  "nutsack", "orgasm", "orgasms", "pawn", "pecker", "penis", "phonesex", "phuck",
  "phuk", "phuked", "phuking", "phukked", "phukking", "phuks", "phuq", "pimp",
  "piss", "pissed", "pisser", "pissers", "pisses", "pissflaps", "pissin",
  "pissing", "pissoff", "poop", "porn", "porno", "pornography", "prick", "pricks",
  "pron", "pube", "pusse", "pussi", "pussies", "pussy", "pussys", "queer", "rectum",
  "retard", "rimjaw", "rimming", "sadist", "schlong", "screwing", "scroat",
  "scrote", "scrotum", "semen", "sex", "shag", "shagger", "shaggin", "shagging",
  "shemale", "shit", "shite", "shited", "shitey", "shitfuck", "shitfull",
  "shithead", "shiting", "shitings", "shits", "shitted", "shitter", "shitters",
  "shitting", "shittings", "shitty", "skank", "slut", "sluts", "smegma", "smut",
  "snatch", "son-of-a-bitch", "spac", "spunk", "s_h_i_t", "t1tt1e5", "t1tties",
  "teets", "teez", "testical", "testicle", "tit", "titfuck", "tits", "titt",
  "tittie5", "tittiefucker", "titties", "tittyfuck", "tittywank", "titwank",
  "tosser", "turd", "twat", "twathead", "twatty", "twunt", "twunter", "v1gra",
  "v1olet", "vag", "vagina", "viagra", "vulva", "wank", "wanker", "wanky",
  "whoar", "whore", "willies", "willy", "xrated", "xxx"
];